import type { ApiError } from './types';

export const API_ERROR: ApiError = {
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_MISSING_JWT: 'AUTH_MISSING_JWT',
  AUTH_PERMISSION: 'AUTH_PERMISSION',
  NO_RESOURCE: 'NO_RESOURCE',
  NO_ROUTE: 'NO_ROUTE',
  BAD_DATA: 'BAD_DATA',
  NOPE: 'NOPE',
};
